// Copyright AudioKit. All Rights Reserved. Revision History at http://github.com/AudioKit/AudioKit/
// This file was auto-autogenerated by scripts and templates at http://github.com/AudioKit/AudioKitDevTools/

import AudioKit
import AudioKitEX
import AVFoundation
import CAudioKitEX

/// A digital effect of talk box. A talk box or talkbox is an effects unit that allows musicians to modify the sound 
/// of a musical instrument by shaping the frequency content of the sound using their mouth. The effect can be used
/// to make a musical instrument sound as if it's speaking, or to create other vocal-like effects.
///
public class Talkbox: Node {
    let input: Node

    /// Connected nodes
    public var connections: [Node] { [input] }

    /// Underlying AVAudioNode
    public var avAudioNode = instantiate(effect: "tbox")

    // MARK: - Parameters

    /// Dry/wet mix.
    public static let balanceDef = NodeParameterDef(
        identifier: "balance",
        name: "Balance",
        address: akGetParameterAddress("TalkboxParameterBalance"),
        defaultValue: 1,
        range: 0 ... 1,
        unit: .percent
    )

    /// Dry/wet mix. Should be a value between 0-1.
    @Parameter(balanceDef) public var balance: AUValue


    // MARK: - Initialization

    /// Initialize this talkbox node
    ///
    /// - Parameters:
    ///   - input: Input node to process
    ///   - balance: dry wet mix
    ///
    public init(
        _ input: Node,
        balance: AUValue = balanceDef.defaultValue
    ) {
        self.input = input

        setupParameters()

        self.balance = balance
    }
}
