# GitHub Actions for SoundpipeAudioKit: includes builds, tests and releases
name: CI

on: [push, pull_request]
env:
  XCODE_VER: latest-stable

jobs:
  test:
    strategy:
      matrix:
        xcode_version: ['13.1']
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - name: Check out SoundpipeAudioKit
        uses: actions/checkout@v2
      - name: Build SoundpipeAudioKit
        run: |
          set -euo pipefail
          swift package clean
          swift build --sanitize="address"
      - name: Run Tests (ASAN)
        run: |
          set -euo pipefail
          xcodebuild -destination 'platform=OS X,arch=x86_64' -scheme SoundpipeAudioKit -enableAddressSanitizer YES test | xcpretty
